title: Mihyeon's blog
author : Mihyeon Jeon
# show_downloads: true
theme: jekyll-theme-minimal
description : A blog about bioinformatics and data engineering

# header_pages:
#   - about.md
#   - blog.md
#   - projects.md
#   - cv_contact.md
